# Not pretty
string(REGEX REPLACE "[.]lib" ".dll" ZLIB_LIBRARY_DEBUG_RUNTIME ${ZLIB_LIBRARY_DEBUG})
string(REGEX REPLACE "/lib/" "/bin/" ZLIB_LIBRARY_DEBUG_RUNTIME ${ZLIB_LIBRARY_DEBUG_RUNTIME})
string(REGEX REPLACE "[.]lib" ".dll" ZLIB_LIBRARY_RELEASE_RUNTIME ${ZLIB_LIBRARY_RELEASE})
string(REGEX REPLACE "/lib/" "/bin/" ZLIB_LIBRARY_RELEASE_RUNTIME ${ZLIB_LIBRARY_RELEASE_RUNTIME})


if(EXISTS "${ZLIB_LIBRARY_RELEASE_RUNTIME}")
  file(COPY_FILE "${ZLIB_LIBRARY_RELEASE_RUNTIME}" "${OUTPUT_DIR}")
endif()
